# Generated by Django 5.0 on 2023-12-28 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ph_no',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.IntegerField(max_length=6),
        ),
    ]
