# Generated by Django 5.0 on 2024-01-04 11:03

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_blogcontent_author_alter_blogpostlike_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='profile_picture',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.profile_picture_path),
        ),
    ]
