# Generated by Django 5.0 on 2024-01-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_historicaluserprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalblogcontent',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
