# Generated by Django 5.0 on 2024-01-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_blogcontent_tag_historicalblogcontent_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalblogcontent',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
    ]
