# Generated by Django 5.0 on 2024-01-10 06:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_tag_remove_blogcontent_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.blog_content_image_path),
        ),
        migrations.AddField(
            model_name='historicalblogcontent',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
