# Generated by Django 5.0 on 2024-01-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='following_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
