# Generated by Django 5.0 on 2024-01-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_historicaluserprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following_count',
        ),
    ]
