# Generated by Django 5.0 on 2024-01-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_historicaluserprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
