# Generated by Django 5.0 on 2024-02-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
